INSERT INTO TB_USUARIO_ROLE (ROLE) VALUES ('PUBLICO');
INSERT INTO TB_USUARIO_ROLE (ROLE) VALUES ('POLICIAL');
INSERT INTO TB_USUARIO_ROLE (ROLE) VALUES ('AGENTE DE SEGURANCA');
INSERT INTO TB_USUARIO_ROLE (ROLE) VALUES ('INVESTIGADOR');
INSERT INTO TB_USUARIO_ROLE (ROLE) VALUES ('GESTOR DE SEGURANCA PUBLICA');